language: node_js
node_js:
    - 0.8
before_script:
    - npm install -g grunt-cli
script:
    - grunt test

notifications:
  email:
    recipients:
      - aserputko@gmail.com
    on_success: never
    on_failure: always